#pragma once

#define MAX_PHASE_SHIFTER_COUNT 8
#define PHASE_SHIFTER_COUNT 4

#define MAX_PHASE_SHIFTER_BIT_RESOLUTION 6
#define PHASE_SHIFTER_BIT_RESOLUTION 4

/*
    SOFT TIMERS CONFIGURATION
*/

#define DEBOUNCE_DURATION_MS 50

#define PS_SELECT_BUTTON_DEBOUNCE_TIMER_ID 0
#define PS_PHASE_BUTTON_DEBOUNCE_TIMER_ID 1
#define PS_LATCH_BUTTON_DEBOUNCE_TIMER_ID 2

#define LONG_PRESS_DURATION_MS 1000

#define PS_SELECT_BUTTON_LONG_PRESS_TIMER_ID 3
#define PS_PHASE_BUTTON_LONG_PRESS_TIMER_ID 4
#define PS_LATCH_BUTTON_LONG_PRESS_TIMER_ID 5
